### ISSUE TITLE
普通java项目如何配置promethues

### ISSUE THREAD

**Issue by liangyuanpeng** [sofastack/sofa-lookout#26]
### Your question

普通java项目如何配置promethues

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFALookout version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by liangyuanpeng** [comment]
都无法请求，这个是如何配置？

http://localhost/metrics

http://localhost:9494/metrics

**Comment by khotyn** [comment]
@liangyuanpeng 你说的普通 Java 项目是指使用了 SOFALookout 的项目还是什么？

**Comment by liangyuanpeng** [comment]
项目是SrpingBoot项目，以普通java项目的方式使用SOFALookout

目前没有使用SOFABoot的计划

**Comment by luyiisme** [comment]
@liangyuanpeng  spring boot也可以用 lookout sofa boot starter的。

另外，普通java项目使用，待会我们补充个文档。更新了，通知你

**Comment by liangyuanpeng** [comment]
好的，明白了！


谢谢！
