### ISSUE TITLE
内置metrics支持

### ISSUE THREAD

**Issue by arebya** [sofastack/sofa-lookout#27]
关于内置的metrics有没有考虑支持更多的公共组件，比如数据库连接池、缓存、httpclient等?

**Comment by luyiisme** [comment]
嗯，我们内部的数据源，缓存等都支持了，但不是以内置的形式。但后续社区的版本，会考虑支持和适配支持主流软件的metrics。 @arebya 可以保持关注，后面我们出这块的方案

**Comment by luyiisme** [comment]
服务器端已开源，可以支持主流的 sdk 工具。也是一种方式，可以解决主要组件的metrics获取问题。
