### ISSUE TITLE
能否提供一个线上的演示地址

### ISSUE THREAD

**Issue by longshang** [sofastack/sofa-lookout#7]
类似点评的CAT提供一个线上体验的地址，对于新手了解有个直观的映像

**Comment by luyiisme** [comment]
@longshang 暂时服务端未开放，所以还无法提供体验地址。 现在可以本地启动prometheus,在其控制台操作，后面我们完善下这块说明。

**Comment by eonezhang** [comment]
@longshang prometheus要怎么从应用中拉取metrics信息呢

**Comment by luyiisme** [comment]
@longshang long 可以看下这个[文章](https://luyiisme.github.io/2018/06/11/lookout-client-and-prometheus/)哦

**Comment by luyiisme** [comment]
https://www.sofastack.tech/sofa-lookout/docs/quickstart-metrics-server 服务器端 quickstart
