### ISSUE TITLE
如何能在服务内部获取到prometheus监控数据？

### ISSUE THREAD

**Issue by hu-chia** [sofastack/sofa-lookout#79]
### Your question

我们已经在使用micrometer了，只想通过sofa-lookout收集一些sofa-rpc相关的监控数据，然后通过我们已有的PushGateway把数据发送到prometheus。

我们希望sofa-lookout的PrometheusRegistry能提供类似于micrometer的PrometheusMeterRegietry的scrap功能，或者通过其他途径能实现类似功能；并且sofa-lookout不应该启动内置的http服务或监听任何端口，这会增加额外的配置和运维压力。

请告诉我是否有任何途径能实现上述功能。

### Environment

- SOFALookout version: 1.4.1
- JVM version (e.g. `java -version`): 13.0.1
- OS version (e.g. `uname -a`): mac/centos7
- Maven version: 3.6.3
- IDE version: IntelliJ IDEA 2019.3

**Comment by ujjboy** [comment]
Hi @guyeu 你的意思是希望 micrometer  能直接采集 sofa-rpc 的数据上报，还是说 micrometer 通过 Lookout 去拿 sofa-rpc 的数据再上报？

目前Lookout 没有单独关端口的能力，只能通过 `com.alipay.sofa.lookout.enable` 来关闭lookout模块

**Comment by hu-chia** [comment]
@ujjboy 最理想的当然是micrometer能直接采集sofa-rpc的数据，比如说sofa-rpc内置一个MeterBinder的实现。

**Comment by ujjboy** [comment]
@guyeu  那你可以直接在 sofa-rpc 工程里增加一个扩展点就可以了，参考目前 lookout 的代码弄一个，不是很难。
参见：https://github.com/sofastack/sofa-rpc/tree/master/extension-impl/metrics-lookout

大概原理就是通过 RPC 的 Filter 拦截或者事件订阅来那你要的值，自己上报。 你可以尝试写写看，贡献给社区，遇到问题随时问我们。
